name: CI/CD Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Verificar arquivos de build
        run: ls -la ./dist/gestao_psicologica_frontend/browser/

  deploy:
    name: Deploy na EC2 - AWS
    runs-on: ubuntu-22.04
    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Executando deploy na EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: '22'
          script: |
            cd /home/ec2-user/gestao_psico

            git -C gestao_psicologica_frontend pull origin main

            docker-compose build frontend_gestao_psicologica

            docker-compose up -d frontend_gestao_psicologica

            docker image prune -f
